name: build-ios
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      # 强制修改 pubspec.yaml，把 intl 版本改成兼容的 0.19.0
      - name: Fix pubspec.yaml
        run: |
          cd simple_live_app
          # 用 sed 强制替换 intl 版本
          sed -i '' 's/intl: ^0.20.2/intl: ^0.19.0/g' pubspec.yaml
          # 清理并安装依赖
          flutter clean
          flutter pub get

      - name: Build iOS
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      - name: Make IPA
        run: |
          cd simple_live_app/build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ios_no_sign.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: simple_live_app/build/ios/iphoneos/ios_no_sign.ipa
