name: build-ios
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5

      # 用稳定版 Flutter，兼容所有依赖
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      # 正常安装依赖，去掉 --force
      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter clean
          flutter pub get

      # 打包 iOS
      - name: Build iOS
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # 生成 IPA
      - name: Make IPA
        run: |
          cd simple_live_app/build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ios_no_sign.ipa Payload

      # 上传 IPA
      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: simple_live_app/build/ios/iphoneos/ios_no_sign.ipa
